<?php
/**
 * @file
 * Code for the Artxchange User feature.
 */

/**
 * Implements hook_menu_alter().
 */
function artx_user_menu_alter(&$items) {
  $items['user/register'] = array(
    'title' => 'Create new account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_register_form_empty'),
    'access callback' => 'user_register_access',
    'type' => MENU_LOCAL_TASK,
  );
  $items['user/register/buyer'] = array(
    'title' => 'As a buyer',
    'description' => 'Demonstrating secondary tabs.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_register_form'),
    'access callback' => 'user_register_access',
    'type' => MENU_LOCAL_TASK,
  );
  $items['user/register/artist'] = array(
    'title' => 'As an artist',
    'description' => 'Demonstrating secondary tabs.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_register_form'),
    'access callback' => 'user_register_access',
    'type' => MENU_LOCAL_TASK,
  );
  $items['user/register/org'] = array(
    'title' => 'As an organization',
    'description' => 'Demonstrating secondary tabs.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_register_form'),
    'access callback' => 'user_register_access',
    'type' => MENU_LOCAL_TASK,
  );
}

/**
 * Form builder; the empty form, wait for role selection
 *
 * @ingroup forms
 * @see user_account_form()
 * @see user_account_form_validate()
 * @see user_register_submit()
 */
function user_register_form_empty($form, &$form_state)
{
  return $form;
}