<?php

global $_LANGMAIL;
$_LANGMAIL = array();

$_LANGMAIL['Newsletter confirmation'] = 'Confirmación de la suscripción a nuestro Boletín de noticias';
$_LANGMAIL['Email verification'] = 'Verificación de correo';
$_LANGMAIL['Newsletter voucher'] = 'Voucher boletín de noticias';
$_LANGMAIL['Your wishlist\\\'s link'] = 'Enlace a su lista de regalos';
$_LANGMAIL['Message from %1$s %2$s'] = 'Mensaje desde %1$s %2$s';
$_LANGMAIL['Your cart and your discount'] = 'Su carrito y descuento';
$_LANGMAIL['Thanks for your order'] = '¡Gracias por su pedido!';
$_LANGMAIL['You are one of our best customers'] = 'Gracias por ser uno de nuestros mejores clientes';
$_LANGMAIL['We miss you'] = 'Lo echamos de menos';
$_LANGMAIL['Product available'] = 'Producto disponible';
$_LANGMAIL['Stock coverage'] = 'Covertura del inventario';
$_LANGMAIL['Product out of stock'] = 'Uno o más productos están agotados';
$_LANGMAIL['Congratulations!'] = '¡Felicidades!';
$_LANGMAIL['%1$s sent you a link to %2$s'] = '%1$s envió un link a %2$s';
$_LANGMAIL['Welcome!'] = '¡Bienvenido!';
$_LANGMAIL['Process the payment of your order'] = 'Proceso de pago de su pedido';
$_LANGMAIL['Your message has been correctly sent #ct%1$s #tc%2$s'] = 'Tu mensaje ha sido enviado correctamente #ct%1$s #tc%2$s';
$_LANGMAIL['Your message has been correctly sent'] = 'Su mensaje se ha enviado correctamente';
$_LANGMAIL['Message from contact form'] = 'Mensaje desde el formulario de contacto';
$_LANGMAIL['New credit slip regarding your order'] = 'Nuevo vale de compra relacionado con su pedido';
$_LANGMAIL['Virtual product to download'] = 'Producto(s) virtual(es) disponibles para descargar';
$_LANGMAIL['Fwd: Customer message'] = 'Fw: Mensaje de cliente';
$_LANGMAIL['Your guest account has been transformed to customer account'] = 'Su cuenta de invitado se transformó en cuenta de cliente';
$_LANGMAIL['Package in transit'] = 'Paquete en camino';
$_LANGMAIL['Log: You have a new alert from your shop'] = 'Log: Tiene una nueva alerta desde su tienda';
$_LANGMAIL['Your order has been changed'] = 'Su pedido se ha modificado';
$_LANGMAIL['Order confirmation'] = 'Confirmación del pedido';
$_LANGMAIL['Message from a customer'] = 'Mensaje de un cliente';
$_LANGMAIL['New message regarding your order'] = 'Nuevo mensaje relacionado con su pedido';
$_LANGMAIL['Your order return state has changed'] = 'El estado de retorno de su orden ha cambiado';
$_LANGMAIL['Your new password'] = 'Su nueva clave';
$_LANGMAIL['Password query confirmation'] = 'Confirmación de clave';
$_LANGMAIL['An answer to your message is available #ct%1$s #tc%2$s'] = 'Una respuesta a su mensaje está disponible en #ct%1$s #tc%2$s';
$_LANGMAIL['New voucher regarding your order %s'] = 'Nuevo bono con respecto a su orden %s';
$_LANGMAIL['New order - #%06d'] = 'Nuevo pedido - #%06d';
