<?php
/**
 * @file
 * Code for the Artxchange User feature.
 */

/**
 * Implements hook_menu_alter().
 */
function artx_gallery_menu()
{
  $items['gallery'] = array(
    'title' => 'Gallery',
    'description' => 'Menu system example using an argument.',
    'page callback' => 'mymodule_page',
//    'page callback' => 'artx_gallery_argument',
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Menu callback; page callback returning an argument.
 */
function artx_gallery_argument($arg1 = "")
{
  global $user;
  if ($arg1 != "") {
    $uid = $user->uid;
    $content['argument_paragraph'] = array(
      '#type' => 'markup',
      '#markup' => '<p>' . t('The argument passed was @arg1.', array('@arg1' => $arg1)) . '</p>',
    );
  } else {
    $content['argument_paragraph'] = array(
      '#type' => 'markup',
      '#markup' => '<p>' . t('These are the hottest gallery of the week:') . '</p>',
    );
  }
  return theme('artx_gallery_default', $content);
}

/**
 * Implements hook_theme().
 */
function artx_gallery_theme($existing, $type, $theme, $path){
  $themes = array(
    'artx_gallery_default' => array(
      'variables' => array('content' => "FOO"),
      'template'  => 'default',
    )
  );
  return $themes;
}

function mymodule_page(){

  $content = array('content' => 'Or grep "function theme_" for more ideas.');
  return theme('artx_gallery_default', $content);
}