<?php

/**
 * implement hook_update_N
 *
 * Add newcol field to {commerce_product} table.
 *
 * note: this is commented out because uid already exists in commerce_product table
 */
//function artx_product_update_7200() {
//  $spec = array(
//    'type' => 'int',
//    'description' => "User Id that owns this product",
//    'length' => 10,
//    'default' => 0,
//    'unsigned' => TRUE,
//    'not null' => TRUE,
//  );
//  db_add_field( 'commerce_product', 'uid', $spec);
//}